import { Injectable } from '@angular/core';
import { Category } from '../models/category.model';
import { Product } from '../models/product.model';

@Injectable({ providedIn: 'root' })
export class ProductService {
  private readonly categories: Category[] = [
    { id: 1, name: 'Smartphones' },
    { id: 2, name: 'Laptops' },
    { id: 3, name: 'Headphones' },
    { id: 4, name: 'Tablets' },
  ];

  private readonly products: Product[] = [
    {
      id: 1,
      categoryId: 1,
      name: 'Смартфон Apple iPhone 15 Pro Max 256Gb серый',
      description: 'Apple iPhone 15 Pro Max - сверхпрочный флагман, изготовленный из титана. За бескомпромиссную производительность смартфона отвечает новейший чип Apple A17 Pro. Устройство получило передовую систему камер, продуманную эргономику, обновленный дизайн и новую программируемую кнопку.',
      price: 729932,
      rating: 4.8,
      likes: 0,
      imageUrl: 'https://resources.cdn-kaspi.kz/img/m/p/ha3/hda/86319874048030.jpg?format=gallery-medium',
      kaspiUrl: 'https://resources.cdn-kaspi.kz/img/m/p/h6d/heb/86319874310174.jpg?format=gallery-medium',
    },
    {
      id: 2,
      categoryId: 1,
      name: 'Смартфон Apple iPhone 14 128Gb черный',
      description: 'Apple iPhone 14 – компактная модель с безрамочным дисплеем OLED 6.1 дюйма. Стеклянный корпус мобильного устройства соответствует стандарту защищенности IP68 – он устойчив к воздействию влаги и пыли.',
      price: 365003,
      rating: 4.7,
      likes: 0,
      imageUrl: 'https://resources.cdn-kaspi.kz/img/m/p/hb8/h19/86042949648414.png?format=gallery-medium',
      kaspiUrl: 'https://resources.cdn-kaspi.kz/img/m/p/h53/h30/86042949779486.png?format=gallery-medium',
    },
    {
      id: 3,
      categoryId: 1,
      name: 'Xiaomi Redmi Note 13 Pro+ 5G 8/256',
      description: 'Fast 5G smartphone with big display and strong value for money.',
      price: 199990,
      rating: 4.6,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=Redmi+Note+13+Pro%2B',
      kaspiUrl: 'https://kaspi.kz/shop/p/xiaomi-redmi-note-13-pro-5g-nfc-8-gb-256-gb-chernyi-116349760/',
    },
    {
      id: 4,
      categoryId: 1,
      name: 'Samsung Galaxy S24 Ultra 12/256',
      description: 'Premium Samsung phone with top camera, display, and flagship performance.',
      price: 749990,
      rating: 4.8,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=Galaxy+S24+Ultra',
      kaspiUrl: 'https://kaspi.kz/shop/p/samsung-galaxy-s24-ultra-5g-12-gb-256-gb-chernyi-podarok-117317266/',
    },
    {
      id: 5,
      categoryId: 1,
      name: 'Google Pixel 8a 8/256',
      description: 'Clean Android, strong camera, and Google’s smart features.',
      price: 329990,
      rating: 4.5,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=Google+Pixel+8a',
      kaspiUrl: 'https://kaspi.kz/shop/p/google-pixel-8a-8-gb-256-gb-chernyi-119617905/',
    },

    {
      id: 6,
      categoryId: 2,
      name: 'Apple MacBook Air 13 (2024) 8/256',
      description: 'Lightweight laptop with great battery life and smooth macOS workflow.',
      price: 549990,
      rating: 4.9,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=MacBook+Air+2024',
      kaspiUrl: 'https://kaspi.kz/shop/p/apple-macbook-air-13-2024-13-6-8-gb-ssd-256-gb-macos-mrxn3-118570205/',
    },
    {
      id: 7,
      categoryId: 2,
      name: 'Lenovo IdeaPad 3 15.6" 8/512',
      description: 'Everyday laptop for study and work: simple, practical, and affordable.',
      price: 259990,
      rating: 4.4,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=Lenovo+IdeaPad+3',
      kaspiUrl: 'https://kaspi.kz/shop/p/lenovo-ideapad-3-15-6-8-gb-ssd-512-gb-dos-15iau7-82rk00evrk-107325644/',
    },
    {
      id: 8,
      categoryId: 2,
      name: 'HP Pavilion 15.6" 16/512',
      description: 'Comfortable screen size and strong RAM/SSD combo for multitasking.',
      price: 389990,
      rating: 4.5,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=HP+Pavilion+15',
      kaspiUrl: 'https://kaspi.kz/shop/p/hp-pavilion-15-6-16-gb-ssd-512-gb-win-11-15-eg3008ci-7p431ea-118374050/',
    },
    {
      id: 9,
      categoryId: 2,
      name: 'Acer Aspire 5 15.6" 8/512',
      description: 'Balanced laptop for school and office tasks with a fast SSD.',
      price: 279990,
      rating: 4.3,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=Acer+Aspire+5',
      kaspiUrl: 'https://kaspi.kz/shop/p/acer-aspire-5-15-6-8-gb-ssd-512-gb-dos-a515-58p-3002-nx-khjer-009-116128645/',
    },
    {
      id: 10,
      categoryId: 2,
      name: 'Huawei MateBook D15 15.6" 8/256',
      description: 'Slim design and good daily performance for students.',
      price: 249990,
      rating: 4.4,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=MateBook+D15',
      kaspiUrl: 'https://kaspi.kz/shop/p/huawei-matebook-d15-15-6-8-gb-ssd-256-gb-win-11-bohrd-wdh9dl-53012uey-104868344/',
    },

    {
      id: 11,
      categoryId: 3,
      name: 'Apple AirPods Pro 2nd',
      description: 'In-ear headphones with active noise cancellation and Apple ecosystem features.',
      price: 109990,
      rating: 4.7,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=AirPods+Pro+2',
      kaspiUrl: 'https://kaspi.kz/shop/p/naushniki-apple-airpods-pro-2nd-belyi-podarok-153601374/',
    },
    {
      id: 12,
      categoryId: 3,
      name: 'Sony WH-1000XM5',
      description: 'Top-tier noise cancelling over-ear headphones with premium sound.',
      price: 189990,
      rating: 4.8,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=Sony+WH-1000XM5',
      kaspiUrl: 'https://kaspi.kz/shop/p/sony-wh-1000xm5-serebristyi-105577599/',
    },
    {
      id: 13,
      categoryId: 3,
      name: 'JBL Tune 510BT',
      description: 'Budget-friendly wireless over-ear headphones for daily listening.',
      price: 16990,
      rating: 4.5,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=JBL+Tune+510BT',
      kaspiUrl: 'https://kaspi.kz/shop/p/jbl-tune-510bt-chernyi-101420081/',
    },
    {
      id: 14,
      categoryId: 3,
      name: 'Marshall Major IV',
      description: 'Iconic Marshall design with long battery life and strong bass.',
      price: 79990,
      rating: 4.6,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=Marshall+Major+IV',
      kaspiUrl: 'https://kaspi.kz/shop/p/naushniki-marshall-major-iv-chernyi-102138144/',
    },
    {
      id: 15,
      categoryId: 3,
      name: 'Xiaomi Redmi Buds 5 Pro',
      description: 'Compact wireless earbuds with a comfortable fit for everyday use.',
      price: 34990,
      rating: 4.4,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=Redmi+Buds+5+Pro',
      kaspiUrl: 'https://kaspi.kz/shop/p/xiaomi-redmi-buds-5-pro-cherno-korichnevyi-117208300/',
    },

    {
      id: 16,
      categoryId: 4,
      name: 'Apple iPad 10.9 (2022) Wi-Fi 64Gb',
      description: 'Great all-round tablet for study, notes, and entertainment.',
      price: 209990,
      rating: 4.7,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=iPad+10.9+2022',
      kaspiUrl: 'https://kaspi.kz/shop/p/apple-ipad-10-9-2022-wi-fi-10-9-djuim-4-gb-64-gb-rozovyi-107266980/',
    },
    {
      id: 17,
      categoryId: 4,
      name: 'Apple iPad Air 10.9 (2022) Wi-Fi 64Gb',
      description: 'Powerful and light tablet for multitasking and creative apps.',
      price: 299990,
      rating: 4.8,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=iPad+Air+2022',
      kaspiUrl: 'https://kaspi.kz/shop/p/apple-ipad-air-2022-10-9-wi-fi-10-9-djuim-8-gb-64-gb-svetlo-bezhevyi-104235603/',
    },
    {
      id: 18,
      categoryId: 4,
      name: 'Samsung Galaxy Tab A9 LTE 8.7" 4/64',
      description: 'Compact LTE tablet for reading, videos, and travel.',
      price: 99990,
      rating: 4.4,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=Galaxy+Tab+A9+LTE',
      kaspiUrl: 'https://kaspi.kz/shop/p/samsung-galaxy-tab-a9-lte-8-7-djuim-4-gb-64-gb-serebristyi-129306976/',
    },
    {
      id: 19,
      categoryId: 4,
      name: 'Samsung Galaxy Tab S9+ 12.4" 12/256',
      description: 'Large high-end tablet with a big screen for productivity and media.',
      price: 499990,
      rating: 4.7,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=Galaxy+Tab+S9%2B',
      kaspiUrl: 'https://kaspi.kz/shop/p/samsung-galaxy-tab-s9-sm-x816-12-4-djuim-12-gb-256-gb-bezhevyi-112455760/',
    },
    {
      id: 20,
      categoryId: 4,
      name: 'Xiaomi Redmi Pad SE Global 11" 8/256',
      description: 'Big display and good memory for a comfortable budget tablet experience.',
      price: 139990,
      rating: 4.5,
      likes: 0,
      imageUrl: 'https://via.placeholder.com/420x280?text=Redmi+Pad+SE+11',
      kaspiUrl: 'https://kaspi.kz/shop/p/xiaomi-redmi-pad-se-global-11-djuim-8-gb-256-gb-fioletovyi-118512731/',
    },
  ];

  getCategories(): Category[] {
    return this.categories.map(c => ({ ...c })); 
  }

  getProductsByCategory(categoryId: number): Product[] {
    return this.products
      .filter(p => p.categoryId === categoryId)
      .map(p => ({ ...p })); 
  }
}